export default {
  FETCH_FAIL: 'BITFINEX/ORDERS_ID/FETCH/FAIL',
  FETCH_ORDERS: 'BITFINEX/ORDERS_ID/FETCH',
  REFRESH: 'BITFINEX/ORDERS_ID/REFRESH',
  SET_PAIRS: 'BITFINEX/ORDERS_ID/PAIR/SET',
  UPDATE_ORDERS: 'BITFINEX/ORDERS_ID/UPDATE',
}
